<?php

	/*
	 * config.base.php
	 *
	 * Description :	Development Site Base Configuration File
	 * 			Auto Generated By Website Installer
	 *
	 * WARNING :	DO NOT EDIT THIS FILE MANUALY.
	 *		AS IT CONTAINS BASIC CONFIGURATION REQUIRED
	 *		TO WORK YOUR SITE PROPERLY
	 *
	 *
	 * Copyright : All rights Reserved under GPL.
	 *
	 * Developed By : Balaji Shinde <balajishinde@benchmarkitsolutions.com>
	 *
	 * Created By :	Balaji Shinde
	 *
	 * Creaded On :	13/09/2011 01:50:00
	 *
	 */

	// Start the Session
	@session_start();

	// Set Site Title
	define('TITLE','Armour Solutions');

	// Set Current Protocol
	define('PROTOCOL',(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https' : 'http');

	// Set Current Host Name
	define('HOST_NAME',$_SERVER['HTTP_HOST']);

	// Set Current Domain Name
	preg_match("/[^\.\/]*\.[^\.\/]+$/", HOST_NAME, $domains);
	$domain_name =  count($domains)>0?array_pop($domains):HOST_NAME;
	define( 'DOMAIN_NAME',$domain_name);

	// Set Base Path
	define('BASE_PATH',str_replace("\\","/",realpath(dirname(__FILE__)."/../").DIRECTORY_SEPARATOR));

	// Set Absolute Path
	define('ABSOLUTE_PATH',strtolower(str_replace($_SERVER['DOCUMENT_ROOT'],"",BASE_PATH)));
	
	// Set Base URL
	define('BASE_URL',PROTOCOL.'://'.HOST_NAME."/".ABSOLUTE_PATH);

	// Set Absolute URL
	define('ABSOLUTE_URL',ABSOLUTE_PATH);

	// Set Server Path/URL
	define('SERVER_PATH',BASE_URL);
	define('SERVER_URL',SERVER_PATH);
	
	

?>